core/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name = 'core'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^post/(?P<pkpost>[0-9]+)/$', views.detail, name='detail'),
]

projetoblog/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

core/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Post(models.Model):
	titulo = models.CharField(max_length=80, verbose_name='Título', blank=False)
	decricao = models.TextField(verbose_name='Texto', blank=False)
	data = models.DateTimeField(default=timezone.now, verbose_name='Data')

	def __str__(self):
		return self.titulo

core/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from .models import Post

# Create your views here.
def index(request):
	posts = Post.objects.all()
	return render(request, 'index.html', {'posts':posts})

def detail(request, pkpost):
	post = get_object_or_404(Post, pk=pkpost)
	return render(request, 'detail.html', {'post': post})

core/templates/detail.html
<!DOCTYPE html>
<html>
<head>
	<title>{{ post.titulo }}</title>
</head>
<body>
<h3>{{ post.titulo }}</h3>
<small>{{ post.data }}</small>
<p>{{ post.decricao }}</p>
</body>
</html>

core/templates/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Blog Django</title>
</head>
<body>
<h3>Postagens</h3>
{% for post in posts %}
	<h4><a href='{% url 'core:detail' post.pk %}'>{{ post.titulo }}</a></h4>
	<p>{{ post.data }}</p><br>
{% empty %}
	<h4>Não há posts publicados</h4>
{% endfor %}
</body>
</html>